[tool.poetry]
name = "pymfy"
version = "0.9.3"
description = "A Somfy Open API library"
authors = ["ETIENNE Thibaut"]
license = "GPL-3.0-only"
readme = "README.md"
homepage = "https://github.com/tetienne/somfy-open-api"
repository = "https://github.com/tetienne/somfy-open-api"

[tool.poetry.dependencies]
python = ">=3.4"
requests-oauthlib = "^1.3.0"
typing = { version = "^3.7.4", python = "<3.5" }

[tool.poetry.dev-dependencies]
tox = ">=3.0"
pytest = ">=4.1"
pytest-cov = ">=2.8.1"
httpretty = ">=1.0.2"
pre-commit = ">=1.10"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
